In [1]:
#Titulo: Laboratorio 2
#fecha: 22 de Mayo
#Autor: Maria Reina Zarate

In [2]:
#Importamos la libreria pandas
import pandas as pd

In [3]:
#Conjunto de datos base para la generación del Big Data
datos = {
    "usuario": ["ana","pepe", "luis","rosita","carolina","paco"],
    "edad":[14,22,35,40,62,70],
    "ciudad": ["cuitlahuac","yanga","atoyac","paraje","fortin", "cuichapa"],
    "compras_realizadas": [5,10,1,2,15,3],
    "activo":[True,True,True,False,True,False],
    "fecha_registro":["2026-01-10","2026-05-21","2026-02-10","2026-03-11","2026-04-15","2026-07-25"]
}

In [4]:
#Creamos el dataframe
dfDatos = pd.DataFrame(datos)

In [5]:
#Mostramos el datos
dfDatos

    usuario  edad      ciudad  compras_realizadas  activo fecha_registro
0       ana    14  cuitlahuac                   5    True     2026-01-10
1      pepe    22       yanga                  10    True     2026-05-21
2      luis    35      atoyac                   1    True     2026-02-10
3    rosita    40      paraje                   2   False     2026-03-11
4  carolina    62      fortin                  15    True     2026-04-15
5      paco    70    cuichapa                   3   False     2026-07-25

In [6]:
#Cantidad de registros a generar aleatoriamente
cantidad= 1000000

In [7]:
import random

In [10]:
#Crear el dataFrame de 1000000 de registros
dfMillon =  pd.DataFrame({
    "nombre": [random.choice(dfDatos["usuario"]) for _ in range(cantidad)],
    "edad":[random.randint(18,80) for _ in range(cantidad)],
    "ciudad":[random.choice(dfDatos["ciudad"]) for _ in range(cantidad)],
    "compras_realizadas": [random.randint(1,10) for _ in range(cantidad)],
    "activo":[random.choice(dfDatos["activo"]) for _ in range(cantidad)],
    "fecha_registro":[random.choice(dfDatos["fecha_registro"]) for _ in range(cantidad)]
})

In [15]:
dfMillon

        nombre  edad      ciudad  compras_realizadas  activo fecha_registro
0         paco    67    cuichapa                   8    True     2026-05-21
1          ana    62    cuichapa                   9    True     2026-04-15
2         pepe    53      paraje                   2    True     2026-05-21
3         luis    33      atoyac                   4    True     2026-01-10
4         pepe    22      atoyac                  10    True     2026-01-10
...        ...   ...         ...                 ...     ...            ...
999995    luis    75  cuitlahuac                  10    True     2026-02-10
999996  rosita    20  cuitlahuac                   3    True     2026-05-21
999997    paco    49      atoyac                   2   False     2026-05-21
999998  rosita    28       yanga                   8   False     2026-07-25
999999  rosita    39      fortin                   9    True     2026-04-15

[1000000 rows x 6 columns]

In [11]:
dfMillon.shape

(1000000, 6)

In [12]:
dfMillon.dtypes

nombre                  str
edad                  int64
ciudad                  str
compras_realizadas    int64
activo                 bool
fecha_registro          str
dtype: object

In [13]:
dfMillon.memory_usage(deep=True)

Index                      132
nombre                61831470
edad                   8000000
ciudad                63832978
compras_realizadas     8000000
activo                 1000000
fecha_registro        67000000
dtype: int64

In [14]:
dfMillon.memory_usage(deep=True).sum()/1024**2

np.float64(199.95172500610352)